version: '3'

services:
  backend:
    build: backend
    depends_on:
      - redis
    environment:
      - REDIS_DNS=redis
  
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - 8080:8080
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=backend
  
  redis:
    image: redis:7.2.0-alpine